### ISSUE TITLE
Validate feed saves it

### ISSUE THREAD

**Issue by ThinkChaos** [pietheinstrengholt/rssmonster#50]
I just got around to testing #49. Validating a feed now adds it to the DB, instead of waiting to click save.

**Comment by pietheinstrengholt** [comment]
The feed processing and Feedparser package is really a can of worms. I’m working on decoupling the logic and have some more generic functions that returns the attributes of a feed, or its items, etc. the latest push I did broke some of the feed resolving since some results are gzipped or encoded. The new fetch method fails resolving these feeds, so I need to revert back some of the logic. Let know when it’s in a decent shape.

**Comment by ThinkChaos** [comment]
I tested the feedparser branch and it works :)
